# Matrix Operation with

### Question: Task 2
A =
\begin{bmatrix}
2 & -1 & 3 \\
0 & 4 & 1
\end{bmatrix}, 
B = 
\begin{bmatrix}
1 & 2 \\
-2 & 0 \\
5 & 3
\end{bmatrix}

1. Identify the number of rows and columns in each matrix.
2. Determine whether the matrices can be multiplied. if so, specify whether its (AB), (BA) or both.
3. if the multiplication is defined, compute the resulting matrix


#### What to do:
A. Numpy computation
B. Markdown Manual computation 

# Solution

### 1. Identify the number of rows and columns in each matrix.

`Matrix A has 2 rows and 3 columns. It is 2 by 3 matrix`

`Matrix B has 3 rows and 2 columns. It is 3 by 2 matrix`


### 2. Determine whether the matrices can be multiplied. if so, specify whether its (AB), (BA) or both.

`The matrices can be multiplied, because the numbers of columns in matrix A is equal to numbers of rows in matrix B`

`Additionally, mutiplication can occur in both AB or BA, Since numbers of column in matrix B is aslo equal to the numbers of rows in matrix A. Hence, they will have different results and also, their result will have different dimensions. AB result will be 2x2, while BA will be 3x3`

### 3. If the multiplication is defined, compute the resulting matrix

#### A. Numpy computation

In [1]:
import numpy as np
# define the array
matrix_A_elements= [[2,-1,3],
                    [0,4,1]]
matrix_A= np.array(matrix_A_elements)
matrix_B_elements= [[1,2],
                    [-2,0],
                    [5,3]]
matrix_B= np.array(matrix_B_elements)
print(f"The order of Matrix A is: {matrix_A.shape}")
print(f"The order of Matrix B is: {matrix_B.shape}")
print("")
# performing multiplication of AB
matrix_AB= matrix_A @ matrix_B
print (f"The Multiplication of matrix A and B is\n {matrix_AB}\n\n")

# performing multiplication of BA
matrix_BA=  matrix_B @ matrix_A
print (f"The Multiplication of matrix B and A is\n {matrix_BA}")


The order of Matrix A is: (2, 3)
The order of Matrix B is: (3, 2)

The Multiplication of matrix A and B is
 [[19 13]
 [-3  3]]


The Multiplication of matrix B and A is
 [[ 2  7  5]
 [-4  2 -6]
 [10  7 18]]


#### B. Markdown Manual computation 

`1. Compute (AB)`

- (A) is **2×3**  
- (B) is **3×2**  
- So the result will be **2×2**

`Row 1 of (A) × columns of (B):`
- ((2 x 1) + (-1 x -2) + (3 x 5)) = 2 + 2 + 15 = 19  
- ((2 x 2) + (-1 x 0) + (3 x 3)) = 4 + 0 + 9 = 13

`Row 2 of (A) × columns of (B):`
- ((0 x 1) + (4 x -2) + (1 x 5) = 0 - 8 + 5 = -3)  
- ((0 x 2) + (4 x 0) + (1 x 3) = 0 + 0 + 3 = 3)  

`Final Result:`
AB =
\begin{bmatrix}
19 & 13 \\
-3 & 3
\end{bmatrix}

`2. Compute (BA)`

- (B) is **3×2**  
- (A) is **2×3**  
- So the result will be **3×3**

`Row 1 of (B) × columns of (A):`
- ((1 x 2) + (2 x 0)) = 2 + 0 = 2  
- ((1 x -1) + (2 x 4)) = -1 + 8 = 7  
- ((1 x 3) + (2 x 1)) = 3 + 2 = 5 

`Row 2 of (B) × columns of (A):`
- ((-2 x 2) + (0 x 0)) = -4 + 0 = -4  
- ((-2 x -1) + (0 x 4)) = 2 + 0 = 2
- ((-2 x 3) + (0 x 1)) = -6 + 0 = -6

`Row 3 of (B) × columns of (A):`
- ((5 x 2) + (3 x 0)) = 10 + 0 = 10  
- ((5 x -1) + (3 x 4)) = -5 + 12 = 7  
- ((5 x 3) + (3 x 1)) = 15 + 3 = 18  

`Final Result:`

BA =
\begin{bmatrix}
2 & 7 & 5 \\
-4 & 2 & -6 \\
10 & 7 & 18
\end{bmatrix}


##### Observation:
- (AB) is a **2×2 matrix**  
- (BA) is a **3×3 matrix**  
Clearly, AB != BA, showing that matrix multiplication is **not commutative**.

# 📘 Matrix Multiplication with NumPy
This repository contains a Jupyter Notebook that demonstrates **matrix operations** as part of the Gen AI Fellowship Programme's **Linear Algebra class**.  
The focus is on solving a matrix multiplication task both **manually (step-by-step)** and **using NumPy in Python**.

---

### 📝 Task Description
We are given two matrices:
A =
\begin{bmatrix}
2 & -1 & 3 \\
0 & 4 & 1
\end{bmatrix},

B =
\begin{bmatrix}
1 & 2 \\
-2 & 0 \\
5 & 3
\end{bmatrix}


`We need to:`
1. Identify the number of rows and columns in each matrix.  
2. Determine whether the matrices can be multiplied (AB, BA, or both).  
3. If multiplication is defined, compute the resulting matrix using:  
   - **A. NumPy computation**  
   - **B. Manual step-by-step computation**

---
### 🚀 Solution Overview
`1. Matrix Dimensions`
- **Matrix A** → 2 × 3  
- **Matrix B** → 3 × 2  

`2. Multiplication Feasibility`
- Both **AB** and **BA** are valid.  
- AB will result in a **2 × 2** matrix.  
- BA will result in a **3 × 3** matrix.  

`3. Results`
- **AB (Manual & NumPy)**  
AB =
\begin{bmatrix}
19 & 13 \\
-3 & 3
\end{bmatrix}

- **BA (NumPy)**  
BA =
\begin{bmatrix}
2 & 7 & 5 \\
-4 & 2 & -6 \\
10 & 7 & 18
\end{bmatrix}

---
### 📂 Repository Structure
├── Matric_multiplication_with_numpy.ipynb

├── README.md

---
### ⚙️ Installation & Setup
Clone the repository and install dependencies:

- git clone https://github.com/Olasquare043/Learning_Linear_Algebra.git
- cd Learning_Linear_Algebra
- pip install numpy

---
### ▶️ Running the Notebook
Launch Jupyter Notebook:
- jupyter notebook Matric_multiplication_with_numpy.ipynb

`Run the cells to see:`
- NumPy computation results
- Manual verification of matrix multiplication

### 🎯 Key Learning Outcomes
- Understand matrix dimensions and multiplication rules.
- Differentiate between AB and BA multiplication.
- Apply both manual computation and NumPy automation.
- Build intuition for linear algebra concepts essential in AI/ML.

### 📌 Author
This notebook was developed as part of the Gen AI Fellowship Programme (Linear Algebra Module).

👤 Saheed Olayinka Olayemi
🔗 https://github.com/Olasquare043