## Question: Task 16
Let A =
\begin{bmatrix}
2 & -1 \\
0 & 3
\end{bmatrix}, 
B = 
\begin{bmatrix}
1 & 4 \\
-2 & 5 \\
\end{bmatrix}
        let the scalars (c=2) (d=3)
1. Compute the following: (cA), (dB), and (c+d)A
2. using the result gotten, verify the scalar multiplication properties
3. find the transpose of both matrices
4. check if (A) and (B) are invertible by computing their determinants. If they invertible, find: A inverse and B inverse 

### 1. Compute the following: (cA), (dB), and (c+d)A

In [35]:
import numpy as np
# define the arrary
A= np.array([[2,-1],[0,3]])
B= np.array([[1,4],[-2,5]])

# set the scalars
c,d =2,3

# compute cA
cA=c*A
print (f"cA is: \n{cA}\n")

# compute dB
dB=d*B
print (f"dB is: \n{dB}\n")

# compute (c+d)A
c_plus_d_A= (c+d)*A
print (f"(c+d)A is: \n{c_plus_d_A}\n")

cA is: 
[[ 4 -2]
 [ 0  6]]

dB is: 
[[ 3 12]
 [-6 15]]

(c+d)A is: 
[[10 -5]
 [ 0 15]]



### 2. using the result gotten, verify the scalar multiplication properties

**Distributivity**: (c+d)A = cA + dA**

In [36]:
# says that (c+d)A = cA + dA
print("Distributivity says: (c+d)A = cA + dA\n")
left = (c+d)*A  # compute (c+d)*A
dA=d*A
right = cA + dA 
print(f'(c+d)A =\n {left}\n')
print(f'cA + dA = \n{right}')
print(f'{"\nYes, it is" if np.array_equal(left,right) else "No,is not"} distributive')

Distributivity says: (c+d)A = cA + dA

(c+d)A =
 [[10 -5]
 [ 0 15]]

cA + dA = 
[[10 -5]
 [ 0 15]]

Yes, it is distributive


### 3. find the transpose of both matrices

In [37]:
# Transpose of Matrix A and B
A_T= np.transpose(A)
B_T= np.transpose(B)
print(f"Transpose of matrix A is: \n {A_T}\n")
print(f"Transpose of matrix B is: \n {B_T}\n")

Transpose of matrix A is: 
 [[ 2  0]
 [-1  3]]

Transpose of matrix B is: 
 [[ 1 -2]
 [ 4  5]]



### 4. check if (A) and (B) are invertible by computing their determinants. If they invertible, find: A inverse and B inverse 

**Checking invertibility**

In [38]:
print("\n" + "="*50)
print("CHECKING INVERTIBILITY")
print("="*50)
# finding the determinant to check invertability
det_A= np.linalg.det(A)  #determinate of A
det_B= np.linalg.det(B)  #determinate of B

# print A and B determinants
print (f"\nDeterminant of A is: {det_A}")
print (f"Determinant of B is: {det_B}\n")
# determine the invertibility, if det ≠ 0
print(f"Is A invertible? {"Yes,(det ≠ 0)" if det_A != 0 else "No, (det = 0)"} ")
print(f"Is B invertible? {"Yes,(det ≠ 0)" if det_B != 0 else "No, (det = 0)"} \n")


CHECKING INVERTIBILITY

Determinant of A is: 6.0
Determinant of B is: 13.0

Is A invertible? Yes,(det ≠ 0) 
Is B invertible? Yes,(det ≠ 0) 



**Computing inverse of matrix A**

In [39]:
# Computing inverse
print("\n" + "="*50)
print("COMPUTING INVERSE OF A")
print("="*50)

# computing for matrix A
if det_A != 0:
    inverse_A= np.linalg.inv(A)
    print(f"\nThe inverse of A is: \n {inverse_A}\n")
    # verification.. A * A^(-1) should produce identity matrix
    print("\nVerification.. A * inverse(A) must give identity matrix:")
    verify=np.dot(A,inverse_A)
    print(verify)
    print (f"\nIs A * inverse(A) = identity matrix? {"Yes" if np.array_equal(verify, np.eye(2)) else "No"}")
else:
    print("\nA is NOT invertible (determinant = 0)")


COMPUTING INVERSE OF A

The inverse of A is: 
 [[0.5        0.16666667]
 [0.         0.33333333]]


Verification.. A * inverse(A) must give identity matrix:
[[1. 0.]
 [0. 1.]]

Is A * inverse(A) = identity matrix? Yes


**Computing inverse of matrix B**

In [40]:
# Computing inverse
print("\n" + "="*50)
print("COMPUTING INVERSE OF B")
print("="*50)

if det_B != 0:
    inverse_B= np.linalg.inv(B)
    print(f"\nThe inverse of B is: \n {inverse_B}\n")
    # verification.. B * B^(-1) should produce identity matrix
    print("\nVerification.. B * inverse(B) must give identity matrix:")
    verify=np.dot(B,inverse_B)
    print(verify)
    print (f"\nIs B * inverse(B) = identity matrix? {"Yes" if np.array_equal(verify, np.eye(2)) else "No"}")
else:
     print("\nB is NOT invertible (determinant = 0)")


COMPUTING INVERSE OF B

The inverse of B is: 
 [[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]


Verification.. B * inverse(B) must give identity matrix:
[[1. 0.]
 [0. 1.]]

Is B * inverse(B) = identity matrix? Yes
