# Student Performance Analysis with Linear Algebra 

## 1. Introduction 
In this case study, we will use Linear Algebra concepts (vectors, vector operations, matrices, 
and matrix operations) to analyze student performance data. 
Linear Algebra is powerful because it allows us to represent and manipulate data in a 
structured way. For example: - Each student’s scores can be represented as a vector. - A group of students’ scores across subjects can be represented as a matrix. - We can then use vector and matrix operations to compute totals, averages, and weighted 
grades.

## 2. Problem Setup 
    We have the scores of 4 students in 3 subjects (Mathematics, English, Science): 

    Student     Math    English     Science 
    Student 1   80      70          90
    Student 2   60      85          75
    Student 3   95      88          92
    Student 4   70      60          65

We will represent this dataset as a matrix: 

\begin{bmatrix}
80 & 70 & 90\\ 
60 & 85 & 75\\
95 & 88 & 92\\ 
70 & 60 & 65 \end{bmatrix}

## 3. Step-by-Step Analysis 

**3.1 Representing Data as a Matrix**

In [50]:
# importing libraries
import numpy as np

student_array=np.array([
    [80, 70, 90], 
    [60, 85, 75], 
    [95, 88, 92], 
    [70, 60, 65]])

**3.2 Total Scores per Student (Vector Addition). Compute the total score for each student by summing across the row vector.**

In [51]:
subject_list= ["Math","English", "Science"]
# define array for total score for each student
total_scores= np.zeros(student_array.shape[0])
for i in range(student_array.shape[0]):
    total_scores[i]=student_array[i,:].sum()
# print(f"old student score is: {student_array}")
print(f"Array sum of each student score is: {total_scores}")

Array sum of each student score is: [240. 220. 275. 195.]


**3.3 Applying Weights (Scalar Multiplication) Apply subject weights (e.g., Math is twice as important as others) using scalar multiplication.**

In [52]:
# applying importance to Math by perform scalar multiplication withon math colum
student_array[:,0]*=3  #column index for math is zero
student_array

array([[240,  70,  90],
       [180,  85,  75],
       [285,  88,  92],
       [210,  60,  65]])

**3.4 Average Score per Subject (Matrix Operations) Compute the average score for each subject by calculating the column-wise mean.**

In [53]:
# define array for total score for each subjects
subject_totals= np.zeros(student_array.shape[1])
for i in range(student_array.shape[1]):
    subject_totals[i]=student_array[:,i].sum()
print(f"Array sum of each subject is: {subject_totals}")

# average score of each subject
Subjects_averages= subject_totals/student_array.shape[0]
print(f"Array average of each subject is: {Subjects_averages}")

Array sum of each subject is: [915. 303. 322.]
Array average of each subject is: [228.75  75.75  80.5 ]


**3.5 Final Grades using Matrix Multiplication Use matrix multiplication with a weight vector (e.g., [0.5, 0.3, 0.2]) to calculate final grades.**

In [54]:
weight_vector= np.array([[0.5],[0.3],[0.2]])

# calculating the final grade by multiply the student scores (4 x 3) by the weight vector (3x1)
final_grades = student_array@ weight_vector
print(f"The final grades are:\n{final_grades}")

The final grades are:
[[159. ]
 [130.5]
 [187.3]
 [136. ]]


**3.6 Comparing Students (Vector Subtraction) 
Compare two students’ performances by subtracting their score vectors.** 

In [55]:
# comparing student 2 and 4 score
student2= student_array[1,:]
student4= student_array[3,:]
# vector subtraction of student 2 and 4 score
comparison= student2-student4
print ("=====================================================")
print ("== Student 2 and Student 4 comparison per subject ===")
print ("=====================================================")
print("")
for i in range(comparison.shape[0]):
    print(f"In {subject_list[i]}: {"Student 4" if comparison[i]<0 else "Student 2"} performed better. Student 2 score {student2[i]} and student 4 has {student4[i]}")

== Student 2 and Student 4 comparison per subject ===

In Math: Student 4 performed better. Student 2 score 180 and student 4 has 210
In English: Student 2 performed better. Student 2 score 85 and student 4 has 60
In Science: Student 2 performed better. Student 2 score 75 and student 4 has 65


## 5 Add-on Exercises 
1. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total 
score and the average per subject. 
2. Suppose one subject (e.g., Science) is 3 times more important than others. Apply scalar 
multiplication and recompute totals. 
3. Define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using 
matrix multiplication. 
4. Compare Student 3 and Student 4 using vector subtraction. Who performed better in each 
subject?

**1. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total score and the average per subject**
**Assuming the list of 4 subjects are:**
- Computer Science (CSC)
- Geography (GEO)
- Statistics (STA)
- English (ENG)

In [56]:
students_data =np.array([
    [82, 60, 89, 79], 
    [66, 65, 71, 39], 
    [55, 88, 92, 71], 
    [77, 69, 65, 44],
    [56, 90, 87, 77]])
subjects= ["Computer Science","Geography", "Statistics","English"]
# define array for total score for each student
student_total_scores= np.zeros(students_data.shape[0])
for i in range(students_data.shape[0]):
    student_total_scores[i]=students_data[i,:].sum()
print(f"Array sum of each student score is: {student_total_scores}")

# define array for total score for each subjects
subject_total_scores= np.zeros(students_data.shape[1])
for i in range(students_data.shape[1]):
    subject_total_scores[i]=students_data[:,i].sum()
print(f"Array sum of each subject is: {subject_total_scores}")

# average score of each subject
Subjects_averages= subject_total_scores/students_data.shape[0]
print(f"Array average of each subject is: {Subjects_averages}")



Array sum of each student score is: [310. 241. 306. 255. 310.]
Array sum of each subject is: [336. 372. 404. 310.]
Array average of each subject is: [67.2 74.4 80.8 62. ]


**2. Suppose one subject (e.g., Science) is 3 times more important than others. Apply scalar multiplication and recompute totals.**
- let say Computer Scvience is 3x over other subjects
- so the scalar will be [3,1,1,1]

In [57]:
# setting scalar
scalar=[3,1,1,1]
# creating empty array
# new_student_data= np.zeros([students_data.shape[0],students_data.shape[1]])
for i, scale in enumerate(scalar):
    students_data[:,i] *= scale
print(f"New Score: \n {students_data}")


# recomputing the totals

# define array for total score for each student
new_student_total_scores= np.zeros(students_data.shape[0])
for i in range(students_data.shape[0]):
    new_student_total_scores[i]=students_data[i,:].sum()
print(f"New Array sum of each student score is: {new_student_total_scores}")

# define array for total score for each subjects
new_subject_total_scores= np.zeros(students_data.shape[1])
for i in range(students_data.shape[1]):
    new_subject_total_scores[i]=students_data[:,i].sum()
print(f"New Array sum of each subject is: {new_subject_total_scores}")


New Score: 
 [[246  60  89  79]
 [198  65  71  39]
 [165  88  92  71]
 [231  69  65  44]
 [168  90  87  77]]
New Array sum of each student score is: [474. 373. 416. 409. 422.]
New Array sum of each subject is: [1008.  372.  404.  310.]


**3. Define new weights for grading (e.g., 35%, 20%, 30%, 15%). Compute final grades using matrix multiplication.**

In [58]:
# assuming the new grade is 45%, 20%, 30%, 15%
weight =np.array([[0.35],[0.2],[0.3],[0.15]])

# using matrix multiplication (5x4) x (4x1) and produce (5x1)
final_grade= np.dot(students_data,weight)

# printing the intial score, score after compute importance and the result after multiplication
print(f"New scores after applied importance: \n {students_data}\n")
print(f"Final grades: \n {final_grade}")

New scores after applied importance: 
 [[246  60  89  79]
 [198  65  71  39]
 [165  88  92  71]
 [231  69  65  44]
 [168  90  87  77]]

Final grades: 
 [[136.65]
 [109.45]
 [113.6 ]
 [120.75]
 [114.45]]


**4. Compare Student 3 and Student 4 using vector subtraction. Who performed better in each  subject?**

In [59]:
# assuming we are using the new scores after adding importance to the sujects
student_3= students_data[2,:]
student_4= students_data[3,:]
compare = student_3 - student_4
# sub=student3-student4
# compare= np.where(sub<0,"Student 4 performed better","Student 3 performed better")
print("\n" + "="*50)
print("The comparison between Student 3 and student 4 ")
print("="*50)
print("")
for i in range(compare.shape[0]):
    # print(f"{subjects[i]}: {compare[i]}")
    print(f"In {subjects[i]}: {"Student 4" if compare[i]<0 else "Student 3"} performed better. Student 3 score {student_3[i]} and student 4 has {student_4[i]}")



The comparison between Student 3 and student 4 

In Computer Science: Student 4 performed better. Student 3 score 165 and student 4 has 231
In Geography: Student 3 performed better. Student 3 score 88 and student 4 has 69
In Statistics: Student 3 performed better. Student 3 score 92 and student 4 has 65
In English: Student 3 performed better. Student 3 score 71 and student 4 has 44
