## Student Performance Analysis with Linear Algebra 

**Add-on Exercises**  
1. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total 
score and the average per subject. 
2. Suppose one subject (e.g., Science) is 3 times more important than others. Apply scalar 
multiplication and recompute totals. 
3. Define new weights for grading (e.g., 40%, 20%, 30%, 10%). Compute final grades using 
matrix multiplication. 
4. Compare Student 3 and Student 4 using vector subtraction. Who performed better in each 
subject?

In [77]:
# importing libraries
import numpy as np


### 1. Create a new 5×4 matrix of scores (5 students, 4 subjects). Compute each student’s total score and the average per subject. 
**Assuming the list of 4 subjects are:**
- Computer Science (CSC)
- Geography (GEO)
- Statistics (STA)
- English (ENG)

In [78]:
students_data =np.array([
    [82, 60, 89, 79], 
    [66, 65, 71, 39], 
    [55, 88, 92, 71], 
    [77, 69, 65, 44],
    [56, 90, 87, 77]])

# define array for total score for each student
student_total_scores= np.zeros(students_data.shape[0])
for i in range(students_data.shape[0]):
    student_total_scores[i]=students_data[i,:].sum()
print(f"Array sum of each student score is: {student_total_scores}")

# define array for total score for each subjects
subject_total_scores= np.zeros(students_data.shape[1])
for i in range(students_data.shape[1]):
    subject_total_scores[i]=students_data[:,i].sum()
print(f"Array sum of each subject is: {subject_total_scores}")

# average score of each subject
Subjects_averages= subject_total_scores/students_data.shape[0]
print(f"Array average of each subject is: {Subjects_averages}")



Array sum of each student score is: [310. 241. 306. 255. 310.]
Array sum of each subject is: [336. 372. 404. 310.]
Array average of each subject is: [67.2 74.4 80.8 62. ]


In [79]:
students_data

array([[82, 60, 89, 79],
       [66, 65, 71, 39],
       [55, 88, 92, 71],
       [77, 69, 65, 44],
       [56, 90, 87, 77]])

### 2. Suppose one subject (e.g., Science) is 3 times more important than others. Apply scalar multiplication and recompute totals. 
- let say Computer Scvience is 3x over other subjects
- so the scalar will be [3,1,1,1]

In [80]:
students_data

array([[82, 60, 89, 79],
       [66, 65, 71, 39],
       [55, 88, 92, 71],
       [77, 69, 65, 44],
       [56, 90, 87, 77]])

In [83]:
# setting scalar
scalar=[3,1,1,1]
# creating empty array
new_student_data= np.zeros([students_data.shape[0],students_data.shape[1]])
for i, scale in enumerate(scalar):
    new_student_data[:,i]= students_data[:,i] * scale
print(f"Old Score: \n {students_data}\n")
print(f"New Score: \n {new_student_data}")


# recomputing the totals

# define array for total score for each student
new_student_total_scores= np.zeros(new_student_data.shape[0])
for i in range(new_student_data.shape[0]):
    new_student_total_scores[i]=new_student_data[i,:].sum()
print(f"New Array sum of each student score is: {new_student_total_scores}")

# define array for total score for each subjects
new_subject_total_scores= np.zeros(new_student_data.shape[1])
for i in range(new_student_data.shape[1]):
    new_subject_total_scores[i]=new_student_data[:,i].sum()
print(f"New Array sum of each subject is: {new_subject_total_scores}")


Old Score: 
 [[82 60 89 79]
 [66 65 71 39]
 [55 88 92 71]
 [77 69 65 44]
 [56 90 87 77]]

New Score: 
 [[246.  60.  89.  79.]
 [198.  65.  71.  39.]
 [165.  88.  92.  71.]
 [231.  69.  65.  44.]
 [168.  90.  87.  77.]]
New Array sum of each student score is: [474. 373. 416. 409. 422.]
New Array sum of each subject is: [1008.  372.  404.  310.]


### 3. Define new weights for grading (e.g., 35%, 20%, 30%, 15%). Compute final grades using matrix multiplication. 


In [84]:
# assuming the new grade is 45%, 20%, 30%, 15%
weight =np.array([[0.35],[0.2],[0.3],[0.15]])

# using matrix multiplication (5x4) x (4x1) and produce (5x1)
final_grade= np.dot(new_student_data,weight)

# printing the intial score, score after compute importance and the result after multiplication
print(f"Old scores: \n {students_data}\n")
print(f"New scores after applied importance: \n {new_student_data}\n")
print(f"Final grades: \n {final_grade}")

Old scores: 
 [[82 60 89 79]
 [66 65 71 39]
 [55 88 92 71]
 [77 69 65 44]
 [56 90 87 77]]

New scores after applied importance: 
 [[246.  60.  89.  79.]
 [198.  65.  71.  39.]
 [165.  88.  92.  71.]
 [231.  69.  65.  44.]
 [168.  90.  87.  77.]]

Final grades: 
 [[136.65]
 [109.45]
 [113.6 ]
 [120.75]
 [114.45]]
